name: Load testing workflow
on: [push, workflow_dispatch]

jobs:
  test:
    name: Run load test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run K6 test test.js
        uses: k6io/action@v0.1
        with:
          filename: test.js
      - name: Run K6 test test-with-additional-metrics.js
        uses: k6io/action@v0.1
        with:
          filename: test-with-additional-metrics.js